default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     5

development:
  <<: *default
  database: partypay_development

test:
  <<: *default
  database: partypay_test

production:
  <<: *default
  database: partypay_production
