# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 920311181f52d8d6b459bf6ad8b58f226c2843528be66a91c128063611263623e67610de83400036890261ed33c4fa670edb78b0f8e83caa0ff7e8cae2f0f327

test:
  secret_key_base: 05a2a7b6349c769e2a7ee88fddc5224739af443ea2f9b8e231c1fde12df9f353fb6a27251c186ba87b7855527036d4258e3c384ee9c608169a022364086e65dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
